source 'https://rubygems.org'

gem 'rails', '4.0.2'
gem 'pg'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-identity'
gem 'newrelic_rpm'
gem 'rest-client'
gem 'jasny_bootstrap_extension_rails'
gem 'fuelux-rails', :git => 'git://github.com/stephenbaldwin/fuelux-rails.git'
gem 'uglifier', '>= 1.3.0'
gem 'less-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer'
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git', :branch => 'bootstrap3'
gem 'momentjs-rails', '~> 2.5.0'
gem 'bootstrap-datetimepicker-rails'
gem "rmagick"
gem "carrierwave"
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'json'

gem 'progress_bar'
gem 'utf8-cleaner'
gem 'geocoder'
gem 'gmaps4rails'
gem 'activerecord-reset-pk-sequence'

group :production do
  gem 'rails_12factor'
end

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do 
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'cucumber-rails'
  gem 'database_cleaner'
end

gem "figaro"